### PR TITLE
ci: add Github Actions

### PR DESCRIPTION
**Pull request by agnes512**
Connects to https://github.com/strongloop/loopback-next/issues/7054
Travis is still available for this repo. Adds Github actions just in case.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-connector-kv-redis) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by agnes512** [comment]
Not sure why it still shows Travis in checks 🤔

**Review by bajtos — APPROVED** [review]
Awesome! 👏🏻 :shipit:

**Comment by bajtos** [comment]
> Not sure why it still shows Travis in checks

I think that's because we still have `.travis.yml` file in our root dir. To disable Travis CI, we have to remove that file.

**Comment by agnes512** [comment]
> > Not sure why it still shows Travis in checks
> 
> I think that's because we still have `.travis.yml` file in our root dir. To disable Travis CI, we have to remove that file.

After I left the comment I realized that (for some reasons) this repo still have Travis available therefore I am keeping both Travis and Github Actions.

**Pull request merged**
